events {}

http {
  upstream frontend_upstream {
    server frontend:3000;
  }

  upstream backend_upstream {
    server backend:8000;
  }

  server {
    listen 80;
    server_name marketrix.ru www.marketrix.ru _;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      if ($host = marketrix.ru) {
        return 301 https://$host$request_uri;
      }
      if ($host = www.marketrix.ru) {
        return 301 https://$host$request_uri;
      }

      proxy_pass http://frontend_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 443 ssl;
    server_name marketrix.ru www.marketrix.ru;

    ssl_certificate /etc/letsencrypt/live/marketrix.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/marketrix.ru/privkey.pem;

    location /api/ {
      proxy_pass http://backend_upstream/api/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://frontend_upstream/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
